### ISSUE TITLE
Question about making updates

### ISSUE THREAD

**Issue by salieflewis** [ourzora/nouns-builder-bot#15]
Hi @IsabellaSmallcombe hope this is the appropriate place to ask this. I've made a PR on the public-assembly-bot repo that adds the 'proposer' field to the Twitter message regarding new proposals. 

When the bot gets redeployed does it look backwards for historical events and tweet those out as well, or only if those events had not been previously tweeted in the past? Basically I'm wondering if when I merge my PR, will the bot try to tweet historical events and error out because those things have already been tweeted?

**Comment by IsabellaSmallcombe** [comment]
hi! it should not if you have redis set up correctly, check your redis and see if you have a variable called `block` . `block` is the last block that your bot looked at during the last tick. the logic is setup to query a range of blocks between the last block looked at and the latest created eth blocks. lmk if it is not working for you!

**Comment by salieflewis** [comment]
Sorry for the late reply, just checked it out and it looks like it is working. 

Last block queried: 16135640

And Etherscan says...

Last finalized block: 16135554
Last safe block: 16135585

I know this is changing in realtime, but it also seems to be a bit ahead of the last finalized block, why is that?

**Comment by IsabellaSmallcombe** [comment]
yep we sit a little bit behind (usually 1 - 2 mins) to make sure the data we want to query is in the api. you could change it but you would start to see missing events as the data does not yet exist in the api

**Comment by salieflewis** [comment]
> yep we sit a little bit behind (usually 1 - 2 mins) to make sure the data we want to query is in the api. you could change it but you would start to see missing events as the data does not yet exist in the api

I was actually saying that it looked like the bot was ahead of the chain! Anyhow, thanks for answering these questions, I'm going to close this issue :)
